# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lights.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0clights.proto\"1\n\x0cLightRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08light_id\x18\x02 \x01(\x05\"/\n\nLightReply\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08light_id\x18\x02 \x01(\x05\x32\x35\n\x06Lights\x12+\n\x0bToggleLight\x12\r.LightRequest\x1a\x0b.LightReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lights_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LIGHTREQUEST._serialized_start=16
  _LIGHTREQUEST._serialized_end=65
  _LIGHTREPLY._serialized_start=67
  _LIGHTREPLY._serialized_end=114
  _LIGHTS._serialized_start=116
  _LIGHTS._serialized_end=169
# @@protoc_insertion_point(module_scope)
