# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lights_pb2 as lights__pb2


class LightsStub(object):
    """The Lights service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ToggleLight = channel.unary_unary(
                '/Lights/ToggleLight',
                request_serializer=lights__pb2.LightRequest.SerializeToString,
                response_deserializer=lights__pb2.LightReply.FromString,
                )


class LightsServicer(object):
    """The Lights service definition.
    """

    def ToggleLight(self, request, context):
        """Sends a 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LightsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ToggleLight': grpc.unary_unary_rpc_method_handler(
                    servicer.ToggleLight,
                    request_deserializer=lights__pb2.LightRequest.FromString,
                    response_serializer=lights__pb2.LightReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Lights', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Lights(object):
    """The Lights service definition.
    """

    @staticmethod
    def ToggleLight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Lights/ToggleLight',
            lights__pb2.LightRequest.SerializeToString,
            lights__pb2.LightReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
